services:
  - type: web
    name: ptt-sentiment-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: "gunicorn app:app"
    autoDeploy: true

  - type: worker
    name: ptt-scheduler
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python scheduler.py"
